module.exports = {
  dataProductsItems : [
      {
        "id": "1",
        "dataTarget": "p-1",
        "dataFilterTarget": "Printed_cotton_quilt",
        "idCart": "p-1",
        "cartTarget": "p-1",
        "product_name": "Printed cotton quilt",
        "product_desc": "Pendleton – Silver City Quilt Set - Soft Cotton Bed Cover - 100% Cotton - Rustic Home Décor - Twin, Full, Queen, and King Blue Mirage - King. ",
        "product_price": "1700",
        "product_size":"King",
        "color":"Blue Mirage",
        "product_image": "/images/Printed_cotton_quilt10.jpg",
        "product_imageView1": "/images/Printed_cotton_quilt11.jpg",
        "product_imageView2": "/images/Printed_cotton_quilt12.jpg",
        "product_imageView3": "/images/Printed_cotton_quilt13.jpg",
        "product_imageView4": "/images/Printed_cotton_quilt14.jpg",
        "added_to_cart": " p-1",
        "idPreview": "img01",
        "idShow": "img01",
      },
      {
        "id": "p-2",
        "dataTarget": "p-2",
        "dataFilterTarget": "Cotton_stripe_quilt",
        "idCart": "p-2",
        "cartTarget": "p-2",
        "product_name": "Cotton stripe quilt",
        "product_desc": "SahSahCasa Quilt King Size, King Quilt Set, Navy Blue Quilt, 100% Cotton King Quilt Bedding Set Bedspreads, Lightweight Reversible Striped Bedspread for... ",
        "product_price": "1700",
        "product_size":"King(98x106)",
        "product_color":"Navy Blue/Grey/White/Striped",
        "product_image": "/images/Cotton_stripe_quilt10.jpg",
        "product_imageView1": "/images/Cotton_stripe_quilt11.jpg",
        "product_imageView2": "/images/Cotton_stripe_quilt12.jpg",
        "product_imageView3": "/images/Cotton_stripe_quilt13.jpg",
        "product_imageView4": "/images/Cotton_stripe_quilt14.jpg",
        "added_to_cart": " p-2",
        "idPreview": "img02",
        "idShow": "img02",
      },
      {
        "id": "p-3",
        "dataTarget": "p-3",
        "dataFilterTarget": "p-3",
        "idCart": "p-3",
        "cartTarget": "p-3",
        "product_name": "Plush cotton quilt",
        "product_desc": "Murano King Quilt - Cotton Washer Print - Plush Back - Size 240*260cm - 7k - Imported High Quality Materials - 3pc (Painting 5) ",
        "product_price": "1,375.00",
        "product_size":"King",
        "product_color":"Graphic 5",
        "product_image": "/images/Plush_cotton_quilt10.jpg",
        "product_imageView1": "/images/Plush_cotton_quilt11.jpg",
        "product_imageView2": "/images/Plush_cotton_quilt12.jpg",
        "product_imageView3": "/images/Plush_cotton_quilt13.jpg",
        "product_imageView4": "/images/Plush_cotton_quilt14.jpg",
        "added_to_cart": " p-3",
        "idPreview": "img03",
        "idShow": "img03",
      },
      {
        "id": "p-4",
        "dataTarget": "p-4",
        "dataFilterTarget": "Plush_stripe_comforter",
        "idCart": "p-4",
        "cartTarget": "p-4",
        "product_name": "Plush stripe comforter",
        "product_desc": "LIFEREVO 3 Pieces Luxury Shaggy Faux Fur Duvet Cover Set Soft Fluffy Fuzzy Comforter Cover Set Striped Printed Furry Long Plush, 1 Duvet Cover+2 Pillow Covers, Zipper Closure,Black and White,Queen ",
        "product_price": "1200",
        "product_size":"King",
        "product_color":"Stripe Print-black",
        "product_image": "/images/Plush_stripe_comforter10.jpg",
        "product_imageView1": "/images/Plush_stripe_comforter11.jpg",
        "product_imageView2": "/images/Plush_stripe_comforter12.jpg",
        "product_imageView3": "/images/Plush_stripe_comforter13.jpg",
        "product_imageView4": "/images/Plush_stripe_comforter14.jpg",
        "added_to_cart": "p-4",
        "idPreview": "img04",
        "idShow": "img04",
      },
      {
        "id": "p-5",
        "dataTarget": "p-5",
        "dataFilterTarget": "Plain_velor_comforter",
        "idCart": "p-5",
        "cartTarget": "p-5",
        "product_name": "Plain velor comforter",
        "product_desc": "Bare Home Comforter Set - Twin/Twin Extra Long Size - Ultra-Soft - Goose Down Alternative - Premium 1800 Series - All Season Warmth (Twin/Twin XL, White)",
        "product_price": "1400",
        "product_size": "Twin/Twin XL",
        "product_color":"01 - White",
        "product_image": "/images/Plain_velor_comforter10.jpg",
        "product_imageView1": "/images/Plain_velor_comforter11.jpg",
        "product_imageView2": "/images/Plain_velor_comforter12.jpg",
        "product_imageView3": "/images/Plain_velor_comforter13.jpg",
        "product_imageView4": "/images/Plain_velor_comforter14.jpg",
        "added_to_cart":"p-5",
        "idPreview": "img05",
        "idShow": "img05",
      },
      {
        "id": "p-6",
        "dataTarget": "p-6",
        "dataFilterTarget": "Printed_Plush_comforter",
        "idCart": "p-6",
        "cartTarget": "p-6",
        "product_name": "Printed Plush comforter",
        "product_desc": "Sleep Philosophy True North Peyton Reversible Fretwork Print Plush Comforter Set Bedroom Comforters with Shams Ultra Soft and Cozy, King, Grey ",
        "product_price": "2300",
        "product_size": "King",
        "product_color":" Grey",
        "product_image": "/images/Printed_Plush_comforter10.jpg",
        "product_imageView1": "/images/Printed_Plush_comforter11.jpg",
        "product_imageView2": "/images/Printed_Plush_comforter12.jpg",
        "product_imageView3": "/images/Printed_Plush_comforter13.jpg",
        "product_imageView4": "/images/Printed_Plush_comforter14.jpg",
        "added_to_cart": "p-6",
        "idPreview": "img06",
        "idShow": "img06",
      },
        {
        "id": "p-8",
        "dataTarget": "p-8",
        "dataFilterTarget": "Printed_cotton_quilt",
        "idCart": "p-8",
        "cartTarget": "p-8",
        "product_name": "Printed cotton quilt",
        "product_desc": "Cozy Line Home Fashions Luxury Classic Bedding Quilt Set, 100% Cotton Beige Blue Floral Pink Flower Bohemian Style Reversible Bedspread Coverlet (Art Painting, King - 3 Piece)",
        "product_price": "1700",
        "product_size": "King",
        "product_color":" Art Painting",
        "product_image": "/images/Printed_cotton_quilt30.jpg",
        "product_imageView1": "/images/Printed_cotton_quilt31.jpg",
        "product_imageView2": "/images/Printed_cotton_quilt32.jpg",
        "product_imageView3": "/images/Printed_cotton_quilt33.jpg",
        "product_imageView4": "/images/Printed_cotton_quilt34.jpg",
        "added_to_cart": " p-8",
        "idPreview": "img08",
        "idShow": "img08",
      },
      {
        "id": "p-9",
        "dataTarget": "p-9",
        "dataFilterTarget": "Printed_cotton_quilt",
        "idCart": "p-9",
        "cartTarget": "p-9",
        "product_name": "Printed cotton quilt",
        "product_desc": "vctops 3 Piece Embroidered Floral Quilted Bedspread Quilt Set 100% Cotton Reversible Patchwork Coverlet Set 1 Quilt and 2 Pillow Shams (Red,Queen)",
        "product_price": "1700",
        "product_size": "King",
        "product_color":" Art Painting",
        "product_image": "/images/Printed_cotton_quilt40.jpg",
        "product_imageView1": "/images/Printed_cotton_quilt41.jpg",
        "product_imageView2": "/images/Printed_cotton_quilt42.jpg",
        "product_imageView3": "/images/Printed_cotton_quilt43.jpg",
        "product_imageView4": "/images/Printed_cotton_quilt44.jpg",
        "added_to_cart": " p-9",
        "idPreview": "img09",
        "idShow": "img09",
      },
      {
        "id": "p-10",
        "dataTarget": "p-10",
        "dataFilterTarget": "Cotton_stripe_quilt",
        "idCart": "p-10",
        "cartTarget": "p-10",
        "product_name": "Cotton stripe quilt",
        "product_desc": "KALOOLA King Quilt Set, 100% Cotton King Quilt Bedding Set, Blue Grey Floral Striped King Bedspread, Farmhouse Reversible Lightweight King Quilt for All Seasons, 3 Pieces",
        "product_price": "2700",
        "product_price": "1700",
        "product_size":"King(98x106)",
        "product_image": "/images/Cotton_stripe_quilt20.jpg",
        "product_imageView1": "/images/Cotton_stripe_quilt21.jpg",
        "product_imageView2": "/images/Cotton_stripe_quilt22.jpg",
        "product_imageView3": "/images/Cotton_stripe_quilt23.jpg",
        "product_imageView4": "/images/Cotton_stripe_quilt24.jpg",
        "added_to_cart": " p-10",
        "idPreview": "img010",
        "idShow": "img010",
      },
      {
        "id": "p-11",
        "dataTarget": "p-11",
        "dataFilterTarget": "Plush_cotton_quilt",
        "idCart": "p-11",
        "cartTarget": "p-11",
        "product_name": "Plush cotton quilt",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "1900",
        "product_image": "/images/Plush_cotton_quilt2.jpg",
        "product_imageView1": "/images/Plush_cotton_quilt2.jpg",
        "product_imageView2": "/images/Plush_cotton_quilt2.jpg",
        "product_imageView3": "/images/Plush_cotton_quilt2.jpg",
        "product_imageView4": "/images/Plush_cotton_quilt2.jpg",
        "product_imageView5": "/images/Plush_cotton_quilt2.jpg",
        "added_to_cart": " p-11",
        "idPreview": "img011",
        "idShow": "img011",
      },
        {
        "id": "p-12",
        "dataTarget": "p-12",
        "dataFilterTarget": "Plush_stripe_comforter",
        "idCart": "p-12",
        "cartTarget": "p-12",
        "product_name": "Plush stripe comforter",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "1200",
        "product_image": "/images/Plush_stripe_comforter2.jpg",
        "product_imageView1": "/images/Plush_stripe_comforter2.jpg",
        "product_imageView2": "/images/Plush_stripe_comforter2.jpg",
        "product_imageView3": "/images/Plush_stripe_comforter2.jpg",
        "product_imageView4": "/images/Plush_stripe_comforter2.jpg",
        "product_imageView5": "/images/Plush_stripe_comforter2.jpg",
        "added_to_cart": "p-12",
        "idPreview": "img012",
        "idShow": "img012",
      },
      {
        "id": "p-13",
        "dataTarget": "p-13",
        "dataFilterTarget": "Plain_velor_comforter",
        "idCart": "p-13",
        "cartTarget": "p-13",
        "product_name": "Plain velor comforter",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "1400",
        "product_image": "/images/Plain_velor_comforter2.jpg",
        "product_imageView1": "/images/Plain_velor_comforter2.jpg",
        "product_imageView2": "/images/Plain_velor_comforter2.jpg",
        "product_imageView3": "/images/Plain_velor_comforter2.jpg",
        "product_imageView4": "/images/Plain_velor_comforter2.jpg",
        "product_imageView5": "/images/Plain_velor_comforter2.jpg",
        "added_to_cart":"p-13",
        "idPreview": "img013",
        "idShow": "img013",
      },
       {
        "id": "p-15",
        "dataTarget": "p-15",
        "dataFilterTarget": "MORA_SPANIEL_BLANKET",
        "idCart": "p-15",
        "cartTarget": "p-15",
        "product_name": "MORA SPANIEL BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/MORA_SPANIEL_BLANKET.jpg",
        "product_imageView1": "/images/MORA_SPANIEL_BLANKET.jpg",
        "product_imageView2": "/images/MORA_SPANIEL_BLANKET.jpg",
        "product_imageView3": "/images/MORA_SPANIEL_BLANKET.jpg",
        "product_imageView4": "/images/MORA_SPANIEL_BLANKET.jpg",
        "product_imageView5": "/images/MORA_SPANIEL_BLANKET.jpg",
        "added_to_cart": "p-15",
        "idPreview": "img015",
        "idShow": "img015",
      },
      {
        "id": "p-16",
        "dataTarget": "p-16",
        "dataFilterTarget": "MORA_SPANIEL_BLANKET",
        "idCart": "p-16",
        "cartTarget": "p-16",
        "product_name": "MORA SPANIEL BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "product_imageView1": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "product_imageView2": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "product_imageView3": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "product_imageView4": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "product_imageView5": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "added_to_cart": "p-16",
        "idPreview": "img016",
        "idShow": "img016",
      },
       {
        "id": "p-17",
        "dataTarget": "p-17",
        "dataFilterTarget": "EGYPTIAN_MURANO_BLANKET",
        "idCart": "p-17",
        "cartTarget": "p-17",
        "product_name": "EGYPTIAN MURANO BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/EGYPTIAN_MURANO_BLANKET.jpg",
        "product_imageView1": "/images/EGYPTIAN_MURANO_BLANKET.jpg",
        "product_imageView2": "/images/EGYPTIAN_MURANO_BLANKET.jpg",
        "product_imageView3": "/images/EGYPTIAN_MURANO_BLANKET.jpg",
        "product_imageView4": "/images/EGYPTIAN_MURANO_BLANKET.jpg",
        "product_imageView5": "/images/EGYPTIAN_MURANO_BLANKET.jpg",
        "added_to_cart": "p-17",
        "idPreview": "img017",
        "idShow": "img017",
      },
       {
        "id": "p-18",
        "dataTarget": "p-18",
        "dataFilterTarget": "EGYPTIAN_MURANO_BLANKET",
        "idCart": "p-18",
        "cartTarget": "p-18",
        "product_name": "EGYPTIAN MURANO BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView1": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView2": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView3": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView4": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView5": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "added_to_cart": "p-18",
        "idPreview": "img018",
        "idShow": "img018",
      },
       {
        "id": "p-19",
        "dataTarget": "p-19",
        "dataFilterTarget": "TURKISH_BLANKET",
        "idCart": "p-19",
        "cartTarget": "p-19",
        "product_name": "TURKISH BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/TURKISH_BLANKET.jpg",
        "product_imageView1": "/images/TURKISH_BLANKET.jpg",
        "product_imageView2": "/images/TURKISH_BLANKET.jpg",
        "product_imageView3": "/images/TURKISH_BLANKET.jpg",
        "product_imageView4": "/images/TURKISH_BLANKET.jpg",
        "product_imageView5": "/images/TURKISH_BLANKET.jpg",
        "added_to_cart": "p-19",
        "idPreview": "img019",
        "idShow": "img019",
      },
      {
        "id": "p-20",
        "dataTarget": "p-20",
        "dataFilterTarget": "TURKISH_BLANKET",
        "idCart": "p-20",
        "cartTarget": "p-20",
        "product_name": "TURKISH BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView1": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView2": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView3": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView4": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView5": "/images/TURKISH_BLANKET2.jpg",
        "added_to_cart": "p-20",
        "idPreview": "img020",
        "idShow": "img020",
      },
      {
        "id": "p-21",
        "dataTarget": "p-21",
        "dataFilterTarget": "PLAIN_COTTON_SHEET",
        "idCart": "p-21",
        "cartTarget": "p-21",
        "product_name": "PLAIN COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView1": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView2": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView3": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView4": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView5": "/images/PLAIN_COTTON_SHEET.jpg",
        "added_to_cart": "p-21",
        "idPreview": "img021",
        "idShow": "img021",
      },
       {
        "id": "p-22",
        "dataTarget": "p-22",
        "dataFilterTarget": "PLAIN_COTTON_SHEET",
        "idCart": "p-22",
        "cartTarget": "p-22",
        "product_name": "PLAIN COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView1": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView2": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView3": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView4": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView5": "/images/PLAIN_COTTON_SHEET2.jpg",
        "added_to_cart": "p-22",
        "idPreview": "img022",
        "idShow": "img022",
      },
      {
        "id": "p-23",
        "dataTarget": "p-23",
        "dataFilterTarget": "COTTON_STRIPE_SHEET",
        "idCart": "p-23",
        "cartTarget": "p-23",
        "product_name": "COTTON STRIPE SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView1": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView2": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView3": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView4": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView5": "/images/COTTON_STRIPE_SHEET.jpg",
        "added_to_cart": "p-23",
        "idPreview": "img023",
        "idShow": "img023",
      },
      {
        "id": "p-24",
        "dataTarget": "p-24",
        "dataFilterTarget": "COTTON_STRIPE_SHEET",
        "idCart": "p-24",
        "cartTarget": "p-24",
        "product_name": "COTTON STRIPE SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView1": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView2": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView3": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView4": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView5": "/images/COTTON_STRIPE_SHEET2.jpg",
        "added_to_cart": "p-24",
        "idPreview": "img024",
        "idShow": "img024",
      },
       {
        "id": "p-25",
        "dataTarget": "p-25",
        "dataFilterTarget": "JACQUARD_COTTON_SHEET",
        "idCart": "p-25",
        "cartTarget": "p-25",
        "product_name": "JACQUARD COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView1": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView2": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView3": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView4": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView5": "/images/JACQUARD_COTTON_SHEET.jpg",
        "added_to_cart": "p-25",
        "idPreview": "img025",
        "idShow": "img025",
      },
         {
        "id": "p-26",
        "dataTarget": "p-26",
        "dataFilterTarget": "JACQUARD_COTTON_SHEET",
        "idCart": "p-26",
        "cartTarget": "p-26",
        "product_name": "JACQUARD COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView1": "images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView2": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView3": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView4": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView5": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "added_to_cart": "p-26",
        "idPreview": "img026",
        "idShow": "img026",
      },
       {
        "id": "p-27",
        "dataTarget": "p-27",
        "dataFilterTarget": "PRINTED_COTTON_SHEET",
        "idCart": "p-27",
        "cartTarget": "p-27",
        "product_name": "PRINTED COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView1": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView2": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView3": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView4": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView5": "/images/PRINTED_COTTON_SHEET.jpg",
        "added_to_cart": "p-27",
        "idPreview": "img027",
        "idShow": "img027",
      },
       {
        "id": "p-28",
        "dataTarget": "p-28",
        "dataFilterTarget": "PRINTED_COTTON_SHEET",
        "idCart": "p-28",
        "cartTarget": "p-28",
        "product_name": "PRINTED COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView1": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView2": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView3": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView4": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView5": "/images/PRINTED_COTTON_SHEET2.jpg",
        "added_to_cart": "p-28",
        "idPreview": "img028",
        "idShow": "img028",
      },
        {
        "id": "p-29",
        "dataTarget": "p-29",
        "dataFilterTarget": "PLAIN_COTTON_COVERTA",
        "idCart": "p-29",
        "cartTarget": "p-29",
        "product_name": "PLAIN COTTON COVERTA",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PLAIN_COTTON_COVERTA.jpg",
        "product_imageView1": "/images/PLAIN_COTTON_COVERTA.jpg",
        "product_imageView2": "/images/PLAIN_COTTON_COVERTA.jpg",
        "product_imageView3": "/images/PLAIN_COTTON_COVERTA.jpg",
        "product_imageView4": "/images/PLAIN_COTTON_COVERTA.jpg",
        "product_imageView5": "/images/PLAIN_COTTON_COVERTA.jpg",
        "added_to_cart": "p-29",
        "idPreview": "img029",
        "idShow": "img029",
      },
          {
        "id": "p-30",
        "dataTarget": "p-30",
        "dataFilterTarget": "PLAIN_COTTON_COVERTA",
        "idCart": "p-30",
        "cartTarget": "p-30",
        "product_name": "PLAIN COTTON COVERTA",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PLAIN_COTTON_COVERTA2.jpg",
        "product_imageView1": "/images/PLAIN_COTTON_COVERTA2.jpg",
        "product_imageView2": "/images/PLAIN_COTTON_COVERTA2.jpg",
        "product_imageView3": "/images/PLAIN_COTTON_COVERTA2.jpg",
        "product_imageView4": "/images/PLAIN_COTTON_COVERTA2.jpg",
        "product_imageView5": "/images/PLAIN_COTTON_COVERTA2.jpg",
        "added_to_cart": "p-30",
        "idPreview": "img030",
        "idShow": "img030",
      },
       {
        "id": "p-31",
        "dataTarget": "p-31",
        "dataFilterTarget": "Capotonian_COTTON_STRIPE_COVERTA",
        "idCart": "p-31",
        "cartTarget": "p-31",
        "product_name": "COTTON STRIPE COVERTA",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/Capotonian_COTTON_STRIPE_COVERTA.jpg",
        "product_imageView1": "/images/Capotonian_COTTON_STRIPE_COVERTA.jpg",
        "product_imageView2": "/images/Capotonian_COTTON_STRIPE_COVERTA.jpg",
        "product_imageView3": "/images/Capotonian_COTTON_STRIPE_COVERTA.jpg",
        "product_imageView4": "/images/Capotonian_COTTON_STRIPE_COVERTA.jpg",
        "product_imageView5": "/images/Capotonian_COTTON_STRIPE_COVERTA.jpg",
        "added_to_cart": "p-31",
        "idPreview": "img031",
        "idShow": "img031",
      },
      {
        "id": "p-32",
        "dataTarget": "p-32",
        "dataFilterTarget": "Capotonian_COTTON_STRIPE_COVERTA",
        "idCart": "p-32",
        "cartTarget": "p-32",
        "product_name": "COTTON STRIPE COVERTA",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/Capotonian_COTTON_STRIPE_COVERTA2.jpg",
        "product_imageView1": "/images/Capotonian_COTTON_STRIPE_COVERTA2.jpg",
        "product_imageView2": "/images/Capotonian_COTTON_STRIPE_COVERTA2.jpg",
        "product_imageView3": "/images/Capotonian_COTTON_STRIPE_COVERTA2.jpg",
        "product_imageView4": "/images/Capotonian_COTTON_STRIPE_COVERTA2.jpg",
        "product_imageView5": "/images/Capotonian_COTTON_STRIPE_COVERTA2.jpg",
        "added_to_cart": "p-32",
        "idPreview": "img032",
        "idShow": "img032",
      },
      {
        "id": "p-33",
        "dataTarget": "p-33",
        "dataFilterTarget": "PILLOW_AND_CUSHION",
        "idCart": "p-33",
        "cartTarget": "p-33",
        "product_name": "PILLOW AND CUSHION",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PILLOW_AND_CUSHION.jpg",
        "product_imageView1": "/images/PILLOW_AND_CUSHION.jpg",
        "product_imageView2": "/images/PILLOW_AND_CUSHION.jpg",
        "product_imageView3": "/images/PILLOW_AND_CUSHION.jpg",
        "product_imageView4": "/images/PILLOW_AND_CUSHION.jpg",
        "product_imageView5": "/images/PILLOW_AND_CUSHION.jpg",
        "added_to_cart": "p-33",
        "idPreview": "img033",
        "idShow": "img033",
      },
      {
        "id": "p-34",
        "dataTarget": "p-34",
        "dataFilterTarget": "PILLOW_AND_CUSHION",
        "idCart": "p-34",
        "cartTarget": "p-34",
        "product_name": "PILLOW AND CUSHION",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PILLOW_AND_CUSHION2.jpg",
        "product_imageView1": "/images/PILLOW_AND_CUSHION2.jpg",
        "product_imageView2": "/images/PILLOW_AND_CUSHION2.jpg",
        "product_imageView3": "/images/PILLOW_AND_CUSHION2.jpg",
        "product_imageView4": "/images/PILLOW_AND_CUSHION2.jpg",
        "product_imageView5": "/images/PILLOW_AND_CUSHION2.jpg",
        "added_to_cart": "p-34",
        "idPreview": "img034",
        "idShow": "img034",
      },
       {
        "id": "p-35",
        "dataTarget": "p-35",
        "dataFilterTarget": "bathrobes",
        "idCart": "p-35",
        "cartTarget": "p-35",
        "product_name": "bathrobes",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/bathrobes.jpg",
        "product_imageView1": "/images/bathrobes.jpg",
        "product_imageView2": "/images/bathrobes.jpg",
        "product_imageView3": "/images/bathrobes.jpg",
        "product_imageView4": "/images/bathrobes.jpg",
        "product_imageView5": "/images/bathrobes.jpg",
        "added_to_cart": "p-35",
        "idPreview": "img035",
        "idShow": "img035",
      },
       {
        "id": "p-36",
        "dataTarget": "p-36",
        "dataFilterTarget": "bathrobes",
        "idCart": "p-36",
        "cartTarget": "p-36",
        "product_name": "bathrobes",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/bathrobes2.jpg",
        "product_imageView1": "/images/bathrobes2.jpg",
        "product_imageView2": "/images/bathrobes2.jpg",
        "product_imageView3": "/images/bathrobes2.jpg",
        "product_imageView4": "/images/bathrobes2.jpg",
        "product_imageView5": "/images/bathrobes2.jpg",
        "added_to_cart": "p-36",
        "idPreview": "img036",
        "idShow": "img036",
      },
         {
        "id": "p-37",
        "dataTarget": "p-37",
        "dataFilterTarget": "bathrobes",
        "idCart": "p-37",
        "cartTarget": "p-37",
        "product_name": "bathrobes",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/bathrobes3.jpg",
        "product_imageView1": "/images/bathrobes3.jpg",
        "product_imageView2": "/images/bathrobes3.jpg",
        "product_imageView3": "/images/bathrobes3.jpg",
        "product_imageView4": "/images/bathrobes3.jpg",
        "product_imageView5": "/images/bathrobes3.jpg",
        "added_to_cart": "p-37",
        "idPreview": "img037",
        "idShow": "img037",
      },
           {
        "id": "p-38",
        "dataTarget": "p-38",
        "dataFilterTarget": "Towels",
        "idCart": "p-38",
        "cartTarget": "p-38",
        "product_name": "Towels",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/Towels.jpg",
        "product_imageView1": "/images/Towels.jpg",
        "product_imageView2": "/images/Towels.jpg",
        "product_imageView3": "/images/Towels.jpg",
        "product_imageView4": "/images/Towels.jpg",
        "product_imageView5": "/images/Towels.jpg",
        "added_to_cart": "p-38",
        "idPreview": "img038",
        "idShow": "img038",
      },     {
        "id": "p-39",
        "dataTarget": "p-39",
        "dataFilterTarget": "Towels",
        "idCart": "p-39",
        "cartTarget": "p-39",
        "product_name": "Towels",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/Towels2.jpg",
        "product_imageView1": "/images/Towels2.jpg",
        "product_imageView2": "/images/Towels2.jpg",
        "product_imageView3": "/images/Towels2.jpg",
        "product_imageView4": "/images/Towels2.jpg",
        "product_imageView5": "/images/Towels2.jpg",
        "added_to_cart": "p-39",
        "idPreview": "img039",
        "idShow": "img039",
      },     {
        "id": "p-40",
        "dataTarget": "p-40",
        "dataFilterTarget": "Towels",
        "idCart": "p-40",
        "cartTarget": "p-40",
        "product_name": "Towels",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/Towels3.jpg",
        "product_imageView1": "/images/Towels3.jpg",
        "product_imageView2": "/images/Towels3.jpg",
        "product_imageView3": "/images/Towels3.jpg",
        "product_imageView4": "/images/Towels3.jpg",
        "product_imageView5": "/images/Towels3.jpg",
        "added_to_cart": "p-40",
        "idPreview": "img040",
        "idShow": "img040",
      },     {
        "id": "p-41",
        "dataTarget": "p-41",
        "dataFilterTarget": "Towels",
        "idCart": "p-41",
        "cartTarget": "p-41",
        "product_name": "Towels",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/Towels4.jpg",
        "product_imageView1": "/images/Towels4.jpg",
        "product_imageView2": "/images/Towels4.jpg",
        "product_imageView3": "/images/Towels4.jpg",
        "product_imageView4": "/images/Towels4.jpg",
        "product_imageView5": "/images/Towels4.jpg",
        "added_to_cart": "p-41",
        "idPreview": "img041",
        "idShow": "img041",
      },
  ],
  dataCarousel : [
    {
      "id": "1",
      "dataTarget": "p-1",
      "dataFilterTarget": "Printed_cotton_quilt",
      "idCart": "p-1",
      "cartTarget": "p-1",
      "product_name": "Printed cotton quilt",
      "product_desc": "Pendleton – Silver City Quilt Set - Soft Cotton Bed Cover - 100% Cotton - Rustic Home Décor - Twin, Full, Queen, and King Blue Mirage - King. ",
      "product_price": "1700",
      "product_size":"King",
      "color":"Blue Mirage",
      "product_image": "/images/Printed_cotton_quilt10.jpg",
      "product_imageView1": "/images/Printed_cotton_quilt11.jpg",
      "product_imageView2": "/images/Printed_cotton_quilt12.jpg",
      "product_imageView3": "/images/Printed_cotton_quilt13.jpg",
      "product_imageView4": "/images/Printed_cotton_quilt14.jpg",
      "added_to_cart": " p-1",
      "idPreview": "img01",
      "idShow": "img01",
    },
    {
      "id": "p-2",
      "dataTarget": "p-2",
      "dataFilterTarget": "Cotton_stripe_quilt",
      "idCart": "p-2",
      "cartTarget": "p-2",
      "product_name": "Cotton stripe quilt",
      "product_desc": "SahSahCasa Quilt King Size, King Quilt Set, Navy Blue Quilt, 100% Cotton King Quilt Bedding Set Bedspreads, Lightweight Reversible Striped Bedspread for... ",
      "product_price": "1700",
      "product_size":"King(98x106)",
      "product_color":"Navy Blue/Grey/White/Striped",
      "product_image": "/images/Cotton_stripe_quilt10.jpg",
      "product_imageView1": "/images/Cotton_stripe_quilt11.jpg",
      "product_imageView2": "/images/Cotton_stripe_quilt12.jpg",
      "product_imageView3": "/images/Cotton_stripe_quilt13.jpg",
      "product_imageView4": "/images/Cotton_stripe_quilt14.jpg",
      "added_to_cart": " p-2",
      "idPreview": "img02",
      "idShow": "img02",
    },
    {
      "id": "p-3",
      "dataTarget": "p-3",
      "dataFilterTarget": "p-3",
      "idCart": "p-3",
      "cartTarget": "p-3",
      "product_name": "Plush cotton quilt",
      "product_desc": "Murano King Quilt - Cotton Washer Print - Plush Back - Size 240*260cm - 7k - Imported High Quality Materials - 3pc (Painting 5) ",
      "product_price": "1,375.00",
      "product_size":"King",
      "product_color":"Graphic 5",
      "product_image": "/images/Plush_cotton_quilt10.jpg",
      "product_imageView1": "/images/Plush_cotton_quilt11.jpg",
      "product_imageView2": "/images/Plush_cotton_quilt12.jpg",
      "product_imageView3": "/images/Plush_cotton_quilt13.jpg",
      "product_imageView4": "/images/Plush_cotton_quilt14.jpg",
      "added_to_cart": " p-3",
      "idPreview": "img03",
      "idShow": "img03",
    },
    {
      "id": "p-4",
      "dataTarget": "p-4",
      "dataFilterTarget": "Plush_stripe_comforter",
      "idCart": "p-4",
      "cartTarget": "p-4",
      "product_name": "Plush stripe comforter",
      "product_desc": "LIFEREVO 3 Pieces Luxury Shaggy Faux Fur Duvet Cover Set Soft Fluffy Fuzzy Comforter Cover Set Striped Printed Furry Long Plush, 1 Duvet Cover+2 Pillow Covers, Zipper Closure,Black and White,Queen ",
      "product_price": "1200",
      "product_size":"King",
      "product_color":"Stripe Print-black",
      "product_image": "/images/Plush_stripe_comforter10.jpg",
      "product_imageView1": "/images/Plush_stripe_comforter11.jpg",
      "product_imageView2": "/images/Plush_stripe_comforter12.jpg",
      "product_imageView3": "/images/Plush_stripe_comforter13.jpg",
      "product_imageView4": "/images/Plush_stripe_comforter14.jpg",
      "added_to_cart": "p-4",
      "idPreview": "img04",
      "idShow": "img04",
    },
    {
      "id": "p-5",
      "dataTarget": "p-5",
      "dataFilterTarget": "Plain_velor_comforter",
      "idCart": "p-5",
      "cartTarget": "p-5",
      "product_name": "Plain velor comforter",
      "product_desc": "Bare Home Comforter Set - Twin/Twin Extra Long Size - Ultra-Soft - Goose Down Alternative - Premium 1800 Series - All Season Warmth (Twin/Twin XL, White)",
      "product_price": "1400",
      "product_size": "Twin/Twin XL",
      "product_color":"01 - White",
      "product_image": "/images/Plain_velor_comforter10.jpg",
      "product_imageView1": "/images/Plain_velor_comforter11.jpg",
      "product_imageView2": "/images/Plain_velor_comforter12.jpg",
      "product_imageView3": "/images/Plain_velor_comforter13.jpg",
      "product_imageView4": "/images/Plain_velor_comforter14.jpg",
      "added_to_cart":"p-5",
      "idPreview": "img05",
      "idShow": "img05",
    },
  ],
  dataSlider : [
    {
        "id": "p-18",
        "dataTarget": "p-18",
        "dataFilterTarget": "EGYPTIAN_MURANO_BLANKET",
        "idCart": "p-18",
        "cartTarget": "p-18",
        "product_name": "EGYPTIAN MURANO BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView1": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView2": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView3": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView4": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView5": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "added_to_cart": "p-18",
        "idPreview": "img018",
        "idShow": "img018",
      },
       {
        "id": "p-19",
        "dataTarget": "p-19",
        "dataFilterTarget": "TURKISH_BLANKET",
        "idCart": "p-19",
        "cartTarget": "p-19",
        "product_name": "TURKISH BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/TURKISH_BLANKET.jpg",
        "product_imageView1": "/images/TURKISH_BLANKET.jpg",
        "product_imageView2": "/images/TURKISH_BLANKET.jpg",
        "product_imageView3": "/images/TURKISH_BLANKET.jpg",
        "product_imageView4": "/images/TURKISH_BLANKET.jpg",
        "product_imageView5": "/images/TURKISH_BLANKET.jpg",
        "added_to_cart": "p-19",
        "idPreview": "img019",
        "idShow": "img019",
      },
      {
        "id": "p-20",
        "dataTarget": "p-20",
        "dataFilterTarget": "TURKISH_BLANKET",
        "idCart": "p-20",
        "cartTarget": "p-20",
        "product_name": "TURKISH BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView1": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView2": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView3": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView4": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView5": "/images/TURKISH_BLANKET2.jpg",
        "added_to_cart": "p-20",
        "idPreview": "img020",
        "idShow": "img020",
      },
      {
        "id": "p-21",
        "dataTarget": "p-21",
        "dataFilterTarget": "PLAIN_COTTON_SHEET",
        "idCart": "p-21",
        "cartTarget": "p-21",
        "product_name": "PLAIN COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView1": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView2": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView3": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView4": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView5": "/images/PLAIN_COTTON_SHEET.jpg",
        "added_to_cart": "p-21",
        "idPreview": "img021",
        "idShow": "img021",
      },
       {
        "id": "p-22",
        "dataTarget": "p-22",
        "dataFilterTarget": "PLAIN_COTTON_SHEET",
        "idCart": "p-22",
        "cartTarget": "p-22",
        "product_name": "PLAIN COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView1": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView2": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView3": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView4": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView5": "/images/PLAIN_COTTON_SHEET2.jpg",
        "added_to_cart": "p-22",
        "idPreview": "img022",
        "idShow": "img022",
      },
      {
        "id": "p-23",
        "dataTarget": "p-23",
        "dataFilterTarget": "COTTON_STRIPE_SHEET",
        "idCart": "p-23",
        "cartTarget": "p-23",
        "product_name": "COTTON STRIPE SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView1": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView2": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView3": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView4": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView5": "/images/COTTON_STRIPE_SHEET.jpg",
        "added_to_cart": "p-23",
        "idPreview": "img023",
        "idShow": "img023",
      },
      {
        "id": "p-24",
        "dataTarget": "p-24",
        "dataFilterTarget": "COTTON_STRIPE_SHEET",
        "idCart": "p-24",
        "cartTarget": "p-24",
        "product_name": "COTTON STRIPE SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView1": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView2": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView3": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView4": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView5": "/images/COTTON_STRIPE_SHEET2.jpg",
        "added_to_cart": "p-24",
        "idPreview": "img024",
        "idShow": "img024",
      },
       {
        "id": "p-25",
        "dataTarget": "p-25",
        "dataFilterTarget": "JACQUARD_COTTON_SHEET",
        "idCart": "p-25",
        "cartTarget": "p-25",
        "product_name": "JACQUARD COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView1": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView2": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView3": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView4": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView5": "/images/JACQUARD_COTTON_SHEET.jpg",
        "added_to_cart": "p-25",
        "idPreview": "img025",
        "idShow": "img025",
      },
         {
        "id": "p-26",
        "dataTarget": "p-26",
        "dataFilterTarget": "JACQUARD_COTTON_SHEET",
        "idCart": "p-26",
        "cartTarget": "p-26",
        "product_name": "JACQUARD COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView1": "images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView2": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView3": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView4": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView5": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "added_to_cart": "p-26",
        "idPreview": "img026",
        "idShow": "img026",
      },
       {
        "id": "p-27",
        "dataTarget": "p-27",
        "dataFilterTarget": "PRINTED_COTTON_SHEET",
        "idCart": "p-27",
        "cartTarget": "p-27",
        "product_name": "PRINTED COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView1": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView2": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView3": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView4": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView5": "/images/PRINTED_COTTON_SHEET.jpg",
        "added_to_cart": "p-27",
        "idPreview": "img027",
        "idShow": "img027",
      },
       {
        "id": "p-28",
        "dataTarget": "p-28",
        "dataFilterTarget": "PRINTED_COTTON_SHEET",
        "idCart": "p-28",
        "cartTarget": "p-28",
        "product_name": "PRINTED COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView1": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView2": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView3": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView4": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView5": "/images/PRINTED_COTTON_SHEET2.jpg",
        "added_to_cart": "p-28",
        "idPreview": "img028",
        "idShow": "img028",
      },
  ],
  dataLatest : [
    {
        "id": "p-18",
        "dataTarget": "p-18",
        "dataFilterTarget": "EGYPTIAN_MURANO_BLANKET",
        "idCart": "p-18",
        "cartTarget": "p-18",
        "product_name": "EGYPTIAN MURANO BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView1": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView2": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView3": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView4": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "product_imageView5": "/images/EGYPTIAN_MURANO_BLANKET2.jpg",
        "added_to_cart": "p-18",
        "idPreview": "img018",
        "idShow": "img018",
      },
       {
        "id": "p-19",
        "dataTarget": "p-19",
        "dataFilterTarget": "TURKISH_BLANKET",
        "idCart": "p-19",
        "cartTarget": "p-19",
        "product_name": "TURKISH BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/TURKISH_BLANKET.jpg",
        "product_imageView1": "/images/TURKISH_BLANKET.jpg",
        "product_imageView2": "/images/TURKISH_BLANKET.jpg",
        "product_imageView3": "/images/TURKISH_BLANKET.jpg",
        "product_imageView4": "/images/TURKISH_BLANKET.jpg",
        "product_imageView5": "/images/TURKISH_BLANKET.jpg",
        "added_to_cart": "p-19",
        "idPreview": "img019",
        "idShow": "img019",
      },
      {
        "id": "p-20",
        "dataTarget": "p-20",
        "dataFilterTarget": "TURKISH_BLANKET",
        "idCart": "p-20",
        "cartTarget": "p-20",
        "product_name": "TURKISH BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView1": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView2": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView3": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView4": "/images/TURKISH_BLANKET2.jpg",
        "product_imageView5": "/images/TURKISH_BLANKET2.jpg",
        "added_to_cart": "p-20",
        "idPreview": "img020",
        "idShow": "img020",
      },
      {
        "id": "p-21",
        "dataTarget": "p-21",
        "dataFilterTarget": "PLAIN_COTTON_SHEET",
        "idCart": "p-21",
        "cartTarget": "p-21",
        "product_name": "PLAIN COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView1": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView2": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView3": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView4": "/images/PLAIN_COTTON_SHEET.jpg",
        "product_imageView5": "/images/PLAIN_COTTON_SHEET.jpg",
        "added_to_cart": "p-21",
        "idPreview": "img021",
        "idShow": "img021",
      },
       {
        "id": "p-22",
        "dataTarget": "p-22",
        "dataFilterTarget": "PLAIN_COTTON_SHEET",
        "idCart": "p-22",
        "cartTarget": "p-22",
        "product_name": "PLAIN COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView1": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView2": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView3": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView4": "/images/PLAIN_COTTON_SHEET2.jpg",
        "product_imageView5": "/images/PLAIN_COTTON_SHEET2.jpg",
        "added_to_cart": "p-22",
        "idPreview": "img022",
        "idShow": "img022",
      },
      {
        "id": "p-23",
        "dataTarget": "p-23",
        "dataFilterTarget": "COTTON_STRIPE_SHEET",
        "idCart": "p-23",
        "cartTarget": "p-23",
        "product_name": "COTTON STRIPE SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView1": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView2": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView3": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView4": "/images/COTTON_STRIPE_SHEET.jpg",
        "product_imageView5": "/images/COTTON_STRIPE_SHEET.jpg",
        "added_to_cart": "p-23",
        "idPreview": "img023",
        "idShow": "img023",
      },
      {
        "id": "p-24",
        "dataTarget": "p-24",
        "dataFilterTarget": "COTTON_STRIPE_SHEET",
        "idCart": "p-24",
        "cartTarget": "p-24",
        "product_name": "COTTON STRIPE SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView1": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView2": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView3": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView4": "/images/COTTON_STRIPE_SHEET2.jpg",
        "product_imageView5": "/images/COTTON_STRIPE_SHEET2.jpg",
        "added_to_cart": "p-24",
        "idPreview": "img024",
        "idShow": "img024",
      },
       {
        "id": "p-25",
        "dataTarget": "p-25",
        "dataFilterTarget": "JACQUARD_COTTON_SHEET",
        "idCart": "p-25",
        "cartTarget": "p-25",
        "product_name": "JACQUARD COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView1": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView2": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView3": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView4": "/images/JACQUARD_COTTON_SHEET.jpg",
        "product_imageView5": "/images/JACQUARD_COTTON_SHEET.jpg",
        "added_to_cart": "p-25",
        "idPreview": "img025",
        "idShow": "img025",
      },
         {
        "id": "p-26",
        "dataTarget": "p-26",
        "dataFilterTarget": "JACQUARD_COTTON_SHEET",
        "idCart": "p-26",
        "cartTarget": "p-26",
        "product_name": "JACQUARD COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView1": "images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView2": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView3": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView4": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "product_imageView5": "/images/JACQUARD_COTTON_SHEET2.jpg",
        "added_to_cart": "p-26",
        "idPreview": "img026",
        "idShow": "img026",
      },
       {
        "id": "p-27",
        "dataTarget": "p-27",
        "dataFilterTarget": "PRINTED_COTTON_SHEET",
        "idCart": "p-27",
        "cartTarget": "p-27",
        "product_name": "PRINTED COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView1": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView2": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView3": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView4": "/images/PRINTED_COTTON_SHEET.jpg",
        "product_imageView5": "/images/PRINTED_COTTON_SHEET.jpg",
        "added_to_cart": "p-27",
        "idPreview": "img027",
        "idShow": "img027",
      },
       {
        "id": "p-28",
        "dataTarget": "p-28",
        "dataFilterTarget": "PRINTED_COTTON_SHEET",
        "idCart": "p-28",
        "cartTarget": "p-28",
        "product_name": "PRINTED COTTON SHEET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView1": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView2": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView3": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView4": "/images/PRINTED_COTTON_SHEET2.jpg",
        "product_imageView5": "/images/PRINTED_COTTON_SHEET2.jpg",
        "added_to_cart": "p-28",
        "idPreview": "img028",
        "idShow": "img028",
      },
  ],
  dataLatestShows : [
    {
        "id": "p-3",
        "dataTarget": "p-3",
        "dataFilterTarget": "p-3",
        "idCart": "p-3",
        "cartTarget": "p-3",
        "product_name": "Plush cotton quilt",
        "product_desc": "Murano King Quilt - Cotton Washer Print - Plush Back - Size 240*260cm - 7k - Imported High Quality Materials - 3pc (Painting 5) ",
        "product_price": "1,375.00",
        "product_size":"King",
        "product_color":"Graphic 5",
        "product_image": "/images/Plush_cotton_quilt10.jpg",
        "product_imageView1": "/images/Plush_cotton_quilt11.jpg",
        "product_imageView2": "/images/Plush_cotton_quilt12.jpg",
        "product_imageView3": "/images/Plush_cotton_quilt13.jpg",
        "product_imageView4": "/images/Plush_cotton_quilt14.jpg",
        "added_to_cart": " p-3",
        "idPreview": "img03",
        "idShow": "img03",
      },
      {
        "id": "p-4",
        "dataTarget": "p-4",
        "dataFilterTarget": "Plush_stripe_comforter",
        "idCart": "p-4",
        "cartTarget": "p-4",
        "product_name": "Plush stripe comforter",
        "product_desc": "LIFEREVO 3 Pieces Luxury Shaggy Faux Fur Duvet Cover Set Soft Fluffy Fuzzy Comforter Cover Set Striped Printed Furry Long Plush, 1 Duvet Cover+2 Pillow Covers, Zipper Closure,Black and White,Queen ",
        "product_price": "1200",
        "product_size":"King",
        "product_color":"Stripe Print-black",
        "product_image": "/images/Plush_stripe_comforter10.jpg",
        "product_imageView1": "/images/Plush_stripe_comforter11.jpg",
        "product_imageView2": "/images/Plush_stripe_comforter12.jpg",
        "product_imageView3": "/images/Plush_stripe_comforter13.jpg",
        "product_imageView4": "/images/Plush_stripe_comforter14.jpg",
        "added_to_cart": "p-4",
        "idPreview": "img04",
        "idShow": "img04",
      },
      {
        "id": "p-5",
        "dataTarget": "p-5",
        "dataFilterTarget": "Plain_velor_comforter",
        "idCart": "p-5",
        "cartTarget": "p-5",
        "product_name": "Plain velor comforter",
        "product_desc": "Bare Home Comforter Set - Twin/Twin Extra Long Size - Ultra-Soft - Goose Down Alternative - Premium 1800 Series - All Season Warmth (Twin/Twin XL, White)",
        "product_price": "1400",
        "product_size": "Twin/Twin XL",
        "product_color":"01 - White",
        "product_image": "/images/Plain_velor_comforter10.jpg",
        "product_imageView1": "/images/Plain_velor_comforter11.jpg",
        "product_imageView2": "/images/Plain_velor_comforter12.jpg",
        "product_imageView3": "/images/Plain_velor_comforter13.jpg",
        "product_imageView4": "/images/Plain_velor_comforter14.jpg",
        "added_to_cart":"p-5",
        "idPreview": "img05",
        "idShow": "img05",
      },
      {
        "id": "p-6",
        "dataTarget": "p-6",
        "dataFilterTarget": "Printed_Plush_comforter",
        "idCart": "p-6",
        "cartTarget": "p-6",
        "product_name": "Printed Plush comforter",
        "product_desc": "Sleep Philosophy True North Peyton Reversible Fretwork Print Plush Comforter Set Bedroom Comforters with Shams Ultra Soft and Cozy, King, Grey ",
        "product_price": "2300",
        "product_size": "King",
        "product_color":" Grey",
        "product_image": "/images/Printed_Plush_comforter10.jpg",
        "product_imageView1": "/images/Printed_Plush_comforter11.jpg",
        "product_imageView2": "/images/Printed_Plush_comforter12.jpg",
        "product_imageView3": "/images/Printed_Plush_comforter13.jpg",
        "product_imageView4": "/images/Printed_Plush_comforter14.jpg",
        "added_to_cart": "p-6",
        "idPreview": "img06",
        "idShow": "img06",
      },
        {
        "id": "p-7",
        "dataTarget": "p-7",
        "dataFilterTarget": "Printed_cotton_quilt",
        "idCart": "p-7",
        "cartTarget": "p-7",
        "product_name": "Printed cotton quilt",
        "product_desc": "Cozy Line Home Fashions Luxury Classic Bedding Quilt Set, 100% Cotton Beige Blue Floral Pink Flower Bohemian Style Reversible Bedspread Coverlet (Art Painting, King - 3 Piece)",
        "product_price": "1700",
        "product_size": "King",
        "product_color":" Art Painting",
        "product_image": "/images/Printed_cotton_quilt20.jpg",
        "product_imageView1": "/images/Printed_cotton_quilt21.jpg",
        "product_imageView2": "/images/Printed_cotton_quilt22.jpg",
        "product_imageView3": "/images/Printed_cotton_quilt23.jpg",
        "product_imageView4": "/images/Printed_cotton_quilt24.jpg",
        "added_to_cart": " p-7",
        "idPreview": "img07",
        "idShow": "img07",
      },
        {
        "id": "p-8",
        "dataTarget": "p-8",
        "dataFilterTarget": "Printed_cotton_quilt",
        "idCart": "p-8",
        "cartTarget": "p-8",
        "product_name": "Printed cotton quilt",
        "product_desc": "Cozy Line Home Fashions Luxury Classic Bedding Quilt Set, 100% Cotton Beige Blue Floral Pink Flower Bohemian Style Reversible Bedspread Coverlet (Art Painting, King - 3 Piece)",
        "product_price": "1700",
        "product_size": "King",
        "product_color":" Art Painting",
        "product_image": "/images/Printed_cotton_quilt30.jpg",
        "product_imageView1": "/images/Printed_cotton_quilt31.jpg",
        "product_imageView2": "/images/Printed_cotton_quilt32.jpg",
        "product_imageView3": "/images/Printed_cotton_quilt33.jpg",
        "product_imageView4": "/images/Printed_cotton_quilt34.jpg",
        "added_to_cart": " p-8",
        "idPreview": "img08",
        "idShow": "img08",
      },
      {
        "id": "p-9",
        "dataTarget": "p-9",
        "dataFilterTarget": "Printed_cotton_quilt",
        "idCart": "p-9",
        "cartTarget": "p-9",
        "product_name": "Printed cotton quilt",
        "product_desc": "vctops 3 Piece Embroidered Floral Quilted Bedspread Quilt Set 100% Cotton Reversible Patchwork Coverlet Set 1 Quilt and 2 Pillow Shams (Red,Queen)",
        "product_price": "1700",
        "product_size": "King",
        "product_color":" Art Painting",
        "product_image": "/images/Printed_cotton_quilt40.jpg",
        "product_imageView1": "/images/Printed_cotton_quilt41.jpg",
        "product_imageView2": "/images/Printed_cotton_quilt42.jpg",
        "product_imageView3": "/images/Printed_cotton_quilt43.jpg",
        "product_imageView4": "/images/Printed_cotton_quilt44.jpg",
        "added_to_cart": " p-9",
        "idPreview": "img09",
        "idShow": "img09",
      },
      {
        "id": "p-10",
        "dataTarget": "p-10",
        "dataFilterTarget": "Cotton_stripe_quilt",
        "idCart": "p-10",
        "cartTarget": "p-10",
        "product_name": "Cotton stripe quilt",
        "product_desc": "KALOOLA King Quilt Set, 100% Cotton King Quilt Bedding Set, Blue Grey Floral Striped King Bedspread, Farmhouse Reversible Lightweight King Quilt for All Seasons, 3 Pieces",
        "product_price": "2700",
        "product_price": "1700",
        "product_size":"King(98x106)",
        "product_image": "/images/Cotton_stripe_quilt20.jpg",
        "product_imageView1": "/images/Cotton_stripe_quilt21.jpg",
        "product_imageView2": "/images/Cotton_stripe_quilt22.jpg",
        "product_imageView3": "/images/Cotton_stripe_quilt23.jpg",
        "product_imageView4": "/images/Cotton_stripe_quilt24.jpg",
        "added_to_cart": " p-10",
        "idPreview": "img010",
        "idShow": "img010",
      },
      {
        "id": "p-11",
        "dataTarget": "p-11",
        "dataFilterTarget": "Plush_cotton_quilt",
        "idCart": "p-11",
        "cartTarget": "p-11",
        "product_name": "Plush cotton quilt",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "1900",
        "product_image": "/images/Plush_cotton_quilt2.jpg",
        "product_imageView1": "/images/Plush_cotton_quilt2.jpg",
        "product_imageView2": "/images/Plush_cotton_quilt2.jpg",
        "product_imageView3": "/images/Plush_cotton_quilt2.jpg",
        "product_imageView4": "/images/Plush_cotton_quilt2.jpg",
        "product_imageView5": "/images/Plush_cotton_quilt2.jpg",
        "added_to_cart": " p-11",
        "idPreview": "img011",
        "idShow": "img011",
      },
        {
        "id": "p-12",
        "dataTarget": "p-12",
        "dataFilterTarget": "Plush_stripe_comforter",
        "idCart": "p-12",
        "cartTarget": "p-12",
        "product_name": "Plush stripe comforter",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "1200",
        "product_image": "/images/Plush_stripe_comforter2.jpg",
        "product_imageView1": "/images/Plush_stripe_comforter2.jpg",
        "product_imageView2": "/images/Plush_stripe_comforter2.jpg",
        "product_imageView3": "/images/Plush_stripe_comforter2.jpg",
        "product_imageView4": "/images/Plush_stripe_comforter2.jpg",
        "product_imageView5": "/images/Plush_stripe_comforter2.jpg",
        "added_to_cart": "p-12",
        "idPreview": "img012",
        "idShow": "img012",
      },
      {
        "id": "p-13",
        "dataTarget": "p-13",
        "dataFilterTarget": "Plain_velor_comforter",
        "idCart": "p-13",
        "cartTarget": "p-13",
        "product_name": "Plain velor comforter",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "1400",
        "product_image": "/images/Plain_velor_comforter2.jpg",
        "product_imageView1": "/images/Plain_velor_comforter2.jpg",
        "product_imageView2": "/images/Plain_velor_comforter2.jpg",
        "product_imageView3": "/images/Plain_velor_comforter2.jpg",
        "product_imageView4": "/images/Plain_velor_comforter2.jpg",
        "product_imageView5": "/images/Plain_velor_comforter2.jpg",
        "added_to_cart":"p-13",
        "idPreview": "img013",
        "idShow": "img013",
      },
       {
        "id": "p-14",
        "dataTarget": "p-14",
        "dataFilterTarget": "Printed_Plush_comforter",
        "idCart": "p-14",
        "cartTarget": "p-14",
        "product_name": "Printed Plush comforter",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/Printed_Plush_comforter2.jpg",
        "product_imageView1": "/images/Printed_Plush_comforter2.jpg",
        "product_imageView2": "/images/Printed_Plush_comforter2.jpg",
        "product_imageView3": "/images/Printed_Plush_comforter2.jpg",
        "product_imageView4": "/images/Printed_Plush_comforter2.jpg",
        "product_imageView5": "/images/Printed_Plush_comforter2.jpg",
        "added_to_cart": "p-14",
        "idPreview": "img014",
        "idShow": "img014",
      },
       {
        "id": "p-15",
        "dataTarget": "p-15",
        "dataFilterTarget": "MORA_SPANIEL_BLANKET",
        "idCart": "p-15",
        "cartTarget": "p-15",
        "product_name": "MORA SPANIEL BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/MORA_SPANIEL_BLANKET.jpg",
        "product_imageView1": "/images/MORA_SPANIEL_BLANKET.jpg",
        "product_imageView2": "/images/MORA_SPANIEL_BLANKET.jpg",
        "product_imageView3": "/images/MORA_SPANIEL_BLANKET.jpg",
        "product_imageView4": "/images/MORA_SPANIEL_BLANKET.jpg",
        "product_imageView5": "/images/MORA_SPANIEL_BLANKET.jpg",
        "added_to_cart": "p-15",
        "idPreview": "img015",
        "idShow": "img015",
      },
      {
        "id": "p-16",
        "dataTarget": "p-16",
        "dataFilterTarget": "MORA_SPANIEL_BLANKET",
        "idCart": "p-16",
        "cartTarget": "p-16",
        "product_name": "MORA SPANIEL BLANKET",
        "product_desc": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
        "product_price": "2300",
        "product_image": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "product_imageView1": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "product_imageView2": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "product_imageView3": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "product_imageView4": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "product_imageView5": "/images/MORA_SPANIEL_BLANKET2.jpg",
        "added_to_cart": "p-16",
        "idPreview": "img016",
        "idShow": "img016",
      },
  ],
};
